#region Copyright

// Copyright 2017 Ralph (Tamaki Hidetsugu)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#endregion

using Diamond.Block;

namespace Diamond.Init
{
    public class Blocks
    {
        public static readonly Block.Block Air;
        public static readonly Block.Block Stone;
        public static readonly Block.Block Grass;
        public static readonly Block.Block Dirt;
        public static readonly Block.Block Cobblestone;
        public static readonly Block.Block Planks;
        public static readonly Block.Block Sapling;
        public static readonly Block.Block Bedrock;
        public static readonly Block.Block FlowingWater;
        public static readonly Block.Block Water;
        public static readonly Block.Block FlowingLava;
        public static readonly Block.Block Lava;
        public static readonly Block.Block Sand;
        public static readonly Block.Block Gravel;
        public static readonly Block.Block GoldOre;
        public static readonly Block.Block IronOre;
        public static readonly Block.Block CoalOre;
        public static readonly Block.Block Log;
        public static readonly Block.Block Log2;
        public static readonly Block.Block Leaves;
        public static readonly Block.Block Leaves2;
        public static readonly Block.Block Sponge;
        public static readonly Block.Block Glass;
        public static readonly Block.Block LapisOre;
        public static readonly Block.Block LapisBlock;
        public static readonly Block.Block Dispenser;
        public static readonly Block.Block SandStone;
        public static readonly Block.Block NoteBlock;
        public static readonly Block.Block Bed;
        public static readonly Block.Block GoldenRail;
        public static readonly Block.Block DetectorRail;
        public static readonly Block.Block StickyPiston;
        public static readonly Block.Block Web;
        public static readonly Block.Block TallGrass;
        public static readonly Block.Block DeadBush;
        public static readonly Block.Block Piston;
        public static readonly Block.Block PistonHead;
        public static readonly Block.Block Wool;
        public static readonly Block.Block PistonExtension;
        public static readonly Block.Block YellowFlower;
        public static readonly Block.Block RedFlower;
        public static readonly Block.Block BrownMushroom;
        public static readonly Block.Block RedMushroom;
        public static readonly Block.Block GoldBlock;
        public static readonly Block.Block IronBlock;
        public static readonly Block.Block DoubleStoneSlab;
        public static readonly Block.Block StoneSlab;
        public static readonly Block.Block BrickBlock;
        public static readonly Block.Block TNT;
        public static readonly Block.Block Bookshelf;
        public static readonly Block.Block MossyCobblestone;
        public static readonly Block.Block Obsidian;
        public static readonly Block.Block Torch;
        public static readonly Block.Block Fire;
        public static readonly Block.Block MobSpawner;
        public static readonly Block.Block OakStairs;
        public static readonly Block.Block Chest;
        public static readonly Block.Block RedstoneWire;
        public static readonly Block.Block DiamondOre;
        public static readonly Block.Block DiamondBlock;
        public static readonly Block.Block CraftingTable;
        public static readonly Block.Block Wheat;
        public static readonly Block.Block Farmland;
        public static readonly Block.Block Furnace;
        public static readonly Block.Block LitFurnace;
        public static readonly Block.Block StandingSign;
        public static readonly Block.Block OakDoor;
        public static readonly Block.Block SpruceDoor;
        public static readonly Block.Block BirchDoor;
        public static readonly Block.Block JungleDoor;
        public static readonly Block.Block AcaciaDoor;
        public static readonly Block.Block DarkOakDoor;
        public static readonly Block.Block Ladder;
        public static readonly Block.Block Rail;
        public static readonly Block.Block StoneStairs;
        public static readonly Block.Block WallSign;
        public static readonly Block.Block Lever;
        public static readonly Block.Block StonePressurePlate;
        public static readonly Block.Block IronDoor;
        public static readonly Block.Block WoodenPressurePlate;
        public static readonly Block.Block RedstoneOre;
        public static readonly Block.Block LitRedstoneOre;
        public static readonly Block.Block UnlitRedstoneTorch;
        public static readonly Block.Block RedstoneTorch;
        public static readonly Block.Block StoneButton;
        public static readonly Block.Block SnowLayer;
        public static readonly Block.Block Ice;
        public static readonly Block.Block Snow;
        public static readonly Block.Block Cactus;
        public static readonly Block.Block Clay;
        public static readonly Block.Block Reeds;
        public static readonly Block.Block Jukebox;
        public static readonly Block.Block OakFence;
        public static readonly Block.Block SpruceFence;
        public static readonly Block.Block BirchFence;
        public static readonly Block.Block JungleFence;
        public static readonly Block.Block DarkOakFence;
        public static readonly Block.Block AcaciaFence;
        public static readonly Block.Block Pumpkin;
        public static readonly Block.Block Netherrack;
        public static readonly Block.Block SoulSand;
        public static readonly Block.Block Glowstone;
        public static readonly Block.Block Portal;
        public static readonly Block.Block LitPumpkin;
        public static readonly Block.Block Cake;
        public static readonly Block.Block UnpoweredRedstoneRepeater;
        public static readonly Block.Block RedstoneRepeater;
        public static readonly Block.Block TrapDoor;
        public static readonly Block.Block MonsterEgg;
        public static readonly Block.Block StoneBrick;
        public static readonly Block.Block BrownMushroomBlock;
        public static readonly Block.Block RedMushroomBlock;
        public static readonly Block.Block IronBars;
        public static readonly Block.Block GlassPane;
        public static readonly Block.Block MelonBlock;
        public static readonly Block.Block PumpkinStem;
        public static readonly Block.Block MelonStem;
        public static readonly Block.Block Vine;
        public static readonly Block.Block OakFenceGate;
        public static readonly Block.Block SpruceFenceGate;
        public static readonly Block.Block BirchFenceGate;
        public static readonly Block.Block JungleFenceGate;
        public static readonly Block.Block DarkOakFenceGate;
        public static readonly Block.Block AcaciaFenceGate;
        public static readonly Block.Block BrickStairs;
        public static readonly Block.Block StoneBrickStairs;
        public static readonly Block.Block Mycelium;
        public static readonly Block.Block WaterLily;
        public static readonly Block.Block NetherBrick;
        public static readonly Block.Block NetherBrickFence;
        public static readonly Block.Block NetherBrickStairs;
        public static readonly Block.Block NetherWart;
        public static readonly Block.Block EnchantingTable;
        public static readonly Block.Block BrewingStand;
        public static readonly Block.Block Cauldron;
        public static readonly Block.Block EndPortal;
        public static readonly Block.Block EndPortalFrame;
        public static readonly Block.Block EndStone;
        public static readonly Block.Block DragonEgg;
        public static readonly Block.Block RedstoneLamp;
        public static readonly Block.Block LitRedstoneLamp;
        public static readonly Block.Block DoubleWoodenSlab;
        public static readonly Block.Block WoodenSlab;
        public static readonly Block.Block Cocoa;
        public static readonly Block.Block SandStoneStairs;
        public static readonly Block.Block EmeraldOre;
        public static readonly Block.Block EnderChest;
        public static readonly Block.Block TripWireHook;
        public static readonly Block.Block TripWire;
        public static readonly Block.Block EmeraldBlock;
        public static readonly Block.Block SpruceStairs;
        public static readonly Block.Block BirchStairs;
        public static readonly Block.Block JungleStairs;
        public static readonly Block.Block CommandBlock;
        public static readonly Block.Block Beacon;
        public static readonly Block.Block CobblestoneWall;
        public static readonly Block.Block FlowerPot;
        public static readonly Block.Block Carrots;
        public static readonly Block.Block Potatoes;
        public static readonly Block.Block WoodenButton;
        public static readonly Block.Block Skull;
        public static readonly Block.Block Anvil;
        public static readonly Block.Block TrappedChest;
        public static readonly Block.Block LightWeightedPressurePlate;
        public static readonly Block.Block HeavyWeightedPressurePlate;
        public static readonly Block.Block UnpoweredComparator;
        public static readonly Block.Block PoweredComparator;
        public static readonly Block.Block DaylightDetector;
        public static readonly Block.Block DaylightDetectorInverted;
        public static readonly Block.Block RedstoneBlock;
        public static readonly Block.Block QuartzOre;
        public static readonly Block.Block Hopper;
        public static readonly Block.Block QuartzBlock;
        public static readonly Block.Block QuartzStairs;
        public static readonly Block.Block ActivatorRail;
        public static readonly Block.Block Dropper;
        public static readonly Block.Block StainedHardenedClay;
        public static readonly Block.Block Barrier;
        public static readonly Block.Block IronTrapDoor;
        public static readonly Block.Block HayBlock;
        public static readonly Block.Block Carpet;
        public static readonly Block.Block HardenedClay;
        public static readonly Block.Block CoalBlock;
        public static readonly Block.Block PackedIce;
        public static readonly Block.Block AcaciaStairs;
        public static readonly Block.Block DarkOakStairs;
        public static readonly Block.Block SlimeBlock;
        public static readonly Block.Block DoublePlant;
        public static readonly Block.Block StainedGlass;
        public static readonly Block.Block StainedGlassPane;
        public static readonly Block.Block Prismarine;
        public static readonly Block.Block SeaLantern;
        public static readonly Block.Block StandingBanner;
        public static readonly Block.Block WallBanner;
        public static readonly Block.Block RedSandStone;
        public static readonly Block.Block RedSandStoneStairs;
        public static readonly Block.Block DoubleStoneSlab2;
        public static readonly Block.Block StoneSlab2;
        public static readonly Block.Block EndRod;
        public static readonly Block.Block ChorusPlant;
        public static readonly Block.Block ChorusFlower;
        public static readonly Block.Block PurpurBlock;
        public static readonly Block.Block PurpurPillar;
        public static readonly Block.Block PurpurStairs;
        public static readonly Block.Block PurpurDoubleSlab;
        public static readonly Block.Block PurpurSlab;
        public static readonly Block.Block EndBricks;
        public static readonly Block.Block Beetroots;
        public static readonly Block.Block GrassPath;
        public static readonly Block.Block EndGateway;
        public static readonly Block.Block RepeatingCommandBlock;
        public static readonly Block.Block ChainCommandBlock;
        public static readonly Block.Block FrostedIce;
        public static readonly Block.Block Magma;
        public static readonly Block.Block NetherWartBlock;
        public static readonly Block.Block RedNetherBrick;
        public static readonly Block.Block BoneBlock;
        public static readonly Block.Block StructureVoid;
        public static readonly Block.Block Observer;
        public static readonly Block.Block WhiteShulkerBox;
        public static readonly Block.Block OrangeShulkerBox;
        public static readonly Block.Block MagentaShulkerBox;
        public static readonly Block.Block LightBlueShulkerBox;
        public static readonly Block.Block YellowShulkerBox;
        public static readonly Block.Block LimeShulkerBox;
        public static readonly Block.Block PinkShulkerBox;
        public static readonly Block.Block GrayShulkerBox;
        public static readonly Block.Block SilverShulkerBox;
        public static readonly Block.Block CyanShulkerBox;
        public static readonly Block.Block PurpleShulkerBox;
        public static readonly Block.Block BlueShulkerBox;
        public static readonly Block.Block BrownShulkerBox;
        public static readonly Block.Block GreenShulkerBox;
        public static readonly Block.Block RedShulkerBox;
        public static readonly Block.Block BlackShulkerBox;
        public static readonly Block.Block StructureBlock;

        static Blocks()
        {
            Air = new BlockAir();
            Stone = new BlockStone();
            Grass = new BlockGrass();
            Dirt = new BlockDirt();
            Cobblestone = new BlockCobblestone();
            Planks = new BlockPlanks();
            Sapling = new BlockSapling();
            Bedrock = new BlockBedrock();
            FlowingWater = new BlockFlowingWater();
            Water = new BlockWater();
            FlowingLava = new BlockFlowingLava();
            Lava = new BlockLava();
            Sand = new BlockSand();
            Gravel = new BlockGravel();
            GoldOre = new BlockGoldOre();
            IronOre = new BlockIronOre();
            CoalOre = new BlockCoalOre();
            Log = new BlockOldLog();
            Log2 = new BlockNewLog();
            Leaves = new BlockOldLeaf();
            Leaves2 = new BlockNewLeaf();
            Sponge = new BlockSponge();
            Glass = new BlockGlass();
            LapisOre = new BlockLapisOre();
            LapisBlock = new BlockLapis();
            Dispenser = new BlockDispenser();
            SandStone = new BlockSandStone();
            NoteBlock = new BlockNote();
            Bed = new BlockBed();
            GoldenRail = new BlockRailPowered();
            DetectorRail = new BlockRailDetector();
            StickyPiston = new BlockStickyPistonBase();
            Web = new BlockWeb();
            TallGrass = new BlockTallGrass();
            DeadBush = new BlockDeadBush();
            Piston = new BlockPistonBase();
            PistonHead = new BlockPistonExtension();
            Wool = new BlockWool();
            PistonExtension = new BlockPistonMoving();
            YellowFlower = new BlockYellowFlower();
            RedFlower = new BlockRedFlower();
            BrownMushroom = new BlockBrownMushroom();
            RedMushroom = new BlockRedMushroom();
            GoldBlock = new BlockGold();
            IronBlock = new BlockIron();
            DoubleStoneSlab = new BlockDoubleStoneSlab();
            StoneSlab = new BlockHalfStoneSlab();
            BrickBlock = new BlockBrick();
            TNT = new BlockTNT();
            Bookshelf = new BlockBookshelf();
            MossyCobblestone = new BlockMossyCobblestone();
            Obsidian = new BlockObsidian();
            Torch = new BlockTorch();
            Fire = new BlockFire();
            MobSpawner = new BlockMobSpawner();
            OakStairs = new BlockOakStairs();
            Chest = new BlockChest();
            RedstoneWire = new BlockRedstoneWire();
            DiamondOre = new BlockDiamondOre();
            DiamondBlock = new BlockDiamond();
            CraftingTable = new BlockWorkbench();
            Wheat = new BlockWheat();
            Farmland = new BlockFarmland();
            Furnace = new BlockFurnace();
            LitFurnace = new BlockLitFurnace();
            StandingSign = new BlockStandingSign();
            OakDoor = new BlockOakDoor();
            SpruceDoor = new BlockSpruceDoor();
            BirchDoor = new BlockBirchDoor();
            JungleDoor = new BlockJungleDoor();
            AcaciaDoor = new BlockAcaciaDoor();
            DarkOakDoor = new BlockDarkOakDoor();
            Ladder = new BlockLadder();
            Rail = new BlockRail();
            StoneStairs = new BlockStoneStairs();
            WallSign = new BlockWallSign();
            Lever = new BlockLever();
            StonePressurePlate = new BlockStonePressurePlate();
            IronDoor = new BlockIronDoor();
            WoodenPressurePlate = new BlockWoodenPressurePlate();
            RedstoneOre = new BlockRedstoneOre();
            LitRedstoneOre = new BlockLitRedstoneOre();
            UnlitRedstoneTorch = new BlockUnlitRedstoneTorch();
            RedstoneTorch = new BlockRedstoneTorch();
            StoneButton = new BlockButtonStone();
            SnowLayer = new BlockSnow();
            Ice = new BlockIce();
            Snow = new BlockSnowBlock();
            Cactus = new BlockCactus();
            Clay = new BlockClay();
            Reeds = new BlockReed();
            Jukebox = new BlockJukebox();
            OakFence = new BlockOakFence();
            SpruceFence = new BlockSpruceFence();
            BirchFence = new BlockBirchFence();
            JungleFence = new BlockJungleFence();
            DarkOakFence = new BlockDarkOakFence();
            AcaciaFence = new BlockAcaciaFence();
            Pumpkin = new BlockPumpkin();
            Netherrack = new BlockNetherrack();
            SoulSand = new BlockSoulSand();
            Glowstone = new BlockGlowstone();
            Portal = new BlockPortal();
            LitPumpkin = new BlockLitPumpkin();
            Cake = new BlockCake();
            UnpoweredRedstoneRepeater = new BlockUnpoweredRedstoneRepeater();
            RedstoneRepeater = new BlockRedstoneRepeater();
            TrapDoor = new BlockTrapDoor();
            MonsterEgg = new BlockSilverfish();
            StoneBrick = new BlockStoneBrick();
            BrownMushroomBlock = new BlockHugeBrownMushroom();
            RedMushroomBlock = new BlockHugeRedMushroom();
            IronBars = new BlockIronPane();
            GlassPane = new BlockGlassPane();
            MelonBlock = new BlockMelon();
            PumpkinStem = new BlockPumpkinStem();
            MelonStem = new BlockMelonStem();
            Vine = new BlockVine();
            OakFenceGate = new BlockOakFenceGate();
            SpruceFenceGate = new BlockSpruceFenceGate();
            BirchFenceGate = new BlockBirchFenceGate();
            JungleFenceGate = new BlockJungleFenceGate();
            DarkOakFenceGate = new BlockDarkOakFenceGate();
            AcaciaFenceGate = new BlockAcaciaFenceGate();
            BrickStairs = new BlockBrickStairs();
            StoneBrickStairs = new BlockStoneBrickStairs();
            Mycelium = new BlockMycelium();
            WaterLily = new BlockLilyPad();
            NetherBrick = new BlockNetherBrick();
            NetherBrickFence = new BlockNetherBrickFence();
            NetherBrickStairs = new BlockNetherBrickStairs();
            NetherWart = new BlockNetherWart();
            EnchantingTable = new BlockEnchantingTable();
            BrewingStand = new BlockBrewingStand();
            Cauldron = new BlockCauldron();
            EndPortal = new BlockEndPortal();
            EndPortalFrame = new BlockEndPotalFrame();
            EndStone = new BlockEndStone();
            DragonEgg = new BlockDragonEgg();
            RedstoneLamp = new BlockRedstoneLight();
            LitRedstoneLamp = new BlockLitRedstoneLight();
            DoubleWoodenSlab = new BlockDoubleWoodSlab();
            WoodenSlab = new BlockHalfWoodSlab();
            Cocoa = new BlockCocoa();
            SandStoneStairs = new BlockSandStoneSiatrs();
            EmeraldOre = new BlockEmeraldOre();
            EnderChest = new BlockEnderChest();
            TripWireHook = new BlockTripWireHook();
            TripWire = new BlockTripWire();
            EmeraldBlock = new BlockEmerald();
            SpruceStairs = new BlockSpruceStairs();
            BirchStairs = new BlockBirchStairs();
            JungleStairs = new BlockJungleStairs();
            CommandBlock = new BlockCommandBlock();
            Beacon = new BlockBeacon();
            CobblestoneWall = new BlockCobblestoneWall();
            FlowerPot = new BlockFlowerPot();
            Carrots = new BlockCarrot();
            Potatoes = new BlockPotato();
            WoodenButton = new BlockButtonWood();
            Skull = new BlockSkull();
            Anvil = new BlockAnvil();
            TrappedChest = new BlockTrapChest();
            LightWeightedPressurePlate = new BlockPressurePlateLightWeighted();
            HeavyWeightedPressurePlate = new BlockPressurePlateHeavyWeighted();
            UnpoweredComparator = new BlockUnpoweredRedstoneComparator();
            PoweredComparator = new BlockRedstoneComparator();
            DaylightDetector = new BlockDaylightDetector();
            DaylightDetectorInverted = new BlockInvertedDaylightDetector();
            RedstoneBlock = new BlockCompressedPowered();
            QuartzOre = new BlockQuartzOre();
            Hopper = new BlockHopper();
            QuartzBlock = new BlockQuartz();
            QuartzStairs = new BlockQuartzStairs();
            ActivatorRail = new BlockActivatorRail();
            Dropper = new BlockDropper();
            StainedHardenedClay = new BlockStainedHardenedClay();
            Barrier = new BlockBarrier();
            IronTrapDoor = new BlockIronTrapDoor();
            HayBlock = new BlockHay();
            Carpet = new BlockCarpet();
            HardenedClay = new BlockHardenedClay();
            CoalBlock = new BlockCoal();
            PackedIce = new BlockPackedIce();
            AcaciaStairs = new BlockAcaciaStairs();
            DarkOakStairs = new BlockDarkOakStairs();
            SlimeBlock = new BlockSlime();
            DoublePlant = new BlockDoublePlant();
            StainedGlass = new BlockStainedGlass();
            StainedGlassPane = new BlockStainedGlassPane();
            Prismarine = new BlockPrismarine();
            SeaLantern = new BlockSeaLantern();
            StandingBanner = new BlockBannerStanding();
            WallBanner = new BlockBannerHanging();
            RedSandStone = new BlockRedSandStone();
            RedSandStoneStairs = new BlockRedSandStoneStairs();
            DoubleStoneSlab2 = new BlockDoubleStoneSlabNew();
            StoneSlab2 = new BlockHalfStoneSlabNew();
            EndRod = new BlockEndRod();
            ChorusPlant = new BlockChorusPlant();
            ChorusFlower = new BlockChorusFlower();
            PurpurBlock = new BlockPurpur();
            PurpurPillar = new BlockPurpurPillar();
            PurpurStairs = new BlockPurpurStairs();
            PurpurDoubleSlab = new BlockPurpurDoubleSlab();
            PurpurSlab = new BlockPurpurHalfSlab();
            EndBricks = new BlockEndBricks();
            Beetroots = new BlockBeetroot();
            GrassPath = new BlockGrassPath();
            EndGateway = new BlockEndGateway();
            RepeatingCommandBlock = new BlockCommandBlockRepeating();
            ChainCommandBlock = new BlockCommandBlockChain();
            FrostedIce = new BlockFrostedIce();
            Magma = new BlockMagma();
            NetherWartBlock = new BlockNetherWartBlock();
            RedNetherBrick = new BlockRedNetherBrick();
            BoneBlock = new BlockBone();
            StructureVoid = new BlockStructureVoid();
            Observer = new BlockObserver();
            WhiteShulkerBox = new BlockShulkerBoxWhite();
            OrangeShulkerBox = new BlockShulkerBoxOrange();
            MagentaShulkerBox = new BlockShulkerBoxMagenta();
            LightBlueShulkerBox = new BlockShulkerBoxLightBlue();
            YellowShulkerBox = new BlockShulkerBoxYellow();
            LimeShulkerBox = new BlockShulkerBoxLime();
            PinkShulkerBox = new BlockShulkerBoxPink();
            GrayShulkerBox = new BlockShulkerBoxGray();
            SilverShulkerBox = new BlockShulkerBoxSilver();
            CyanShulkerBox = new BlockShulkerBoxCyan();
            PurpleShulkerBox = new BlockShulkerBoxPurple();
            BlueShulkerBox = new BlockShulkerBoxBlue();
            BrownShulkerBox = new BlockShulkerBoxBrown();
            GreenShulkerBox = new BlockShulkerBoxGreen();
            RedShulkerBox = new BlockShulkerBoxRed();
            BlackShulkerBox = new BlockShulkerBoxBlack();
            StructureBlock = new BlockStructure();
        }
    }
}