#region Copyright

// Copyright 2017 Ralph (Tamaki Hidetsugu)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#endregion

using Diamond.Blocks;

namespace Diamond.Init
{
    public class Blocks
    {
        public static readonly Block Air;
        public static readonly Block Stone;
        public static readonly Block Grass;
        public static readonly Block Dirt;
        public static readonly Block Cobblestone;
        public static readonly Block Planks;
        public static readonly Block Sapling;
        public static readonly Block Bedrock;
        public static readonly Block FlowingWater;
        public static readonly Block Water;
        public static readonly Block FlowingLava;
        public static readonly Block Lava;
        public static readonly Block Sand;
        public static readonly Block Gravel;
        public static readonly Block GoldOre;
        public static readonly Block IronOre;
        public static readonly Block CoalOre;
        public static readonly Block Log;
        public static readonly Block Log2;
        public static readonly Block Leaves;
        public static readonly Block Leaves2;
        public static readonly Block Sponge;
        public static readonly Block Glass;
        public static readonly Block LapisOre;
        public static readonly Block LapisBlock;
        public static readonly Block Dispenser;
        public static readonly Block SandStone;
        public static readonly Block NoteBlock;
        public static readonly Block Bed;
        public static readonly Block GoldenRail;
        public static readonly Block DetectorRail;
        public static readonly Block StickyPiston;
        public static readonly Block Web;
        public static readonly Block TallGrass;
        public static readonly Block DeadBush;
        public static readonly Block Piston;
        public static readonly Block PistonHead;
        public static readonly Block Wool;
        public static readonly Block PistonExtension;
        public static readonly Block YellowFlower;
        public static readonly Block RedFlower;
        public static readonly Block BrownMushroom;
        public static readonly Block RedMushroom;
        public static readonly Block GoldBlock;
        public static readonly Block IronBlock;
        public static readonly Block DoubleStoneSlab;
        public static readonly Block StoneSlab;
        public static readonly Block BrickBlock;
        public static readonly Block TNT;
        public static readonly Block Bookshelf;
        public static readonly Block MossyCobblestone;
        public static readonly Block Obsidian;
        public static readonly Block Torch;
        public static readonly Block Fire;
        public static readonly Block MobSpawner;
        public static readonly Block OakStairs;
        public static readonly Block Chest;
        public static readonly Block RedstoneWire;
        public static readonly Block DiamondOre;
        public static readonly Block DiamondBlock;
        public static readonly Block CraftingTable;
        public static readonly Block Wheat;
        public static readonly Block Farmland;
        public static readonly Block Furnace;
        public static readonly Block LitFurnace;
        public static readonly Block StandingSign;
        public static readonly Block OakDoor;
        public static readonly Block SpruceDoor;
        public static readonly Block BirchDoor;
        public static readonly Block JungleDoor;
        public static readonly Block AcaciaDoor;
        public static readonly Block DarkOakDoor;
        public static readonly Block Ladder;
        public static readonly Block Rail;
        public static readonly Block StoneStairs;
        public static readonly Block WallSign;
        public static readonly Block Lever;
        public static readonly Block StonePressurePlate;
        public static readonly Block IronDoor;
        public static readonly Block WoodenPressurePlate;
        public static readonly Block RedstoneOre;
        public static readonly Block LitRedstoneOre;
        public static readonly Block UnlitRedstoneTorch;
        public static readonly Block RedstoneTorch;
        public static readonly Block StoneButton;
        public static readonly Block SnowLayer;
        public static readonly Block Ice;
        public static readonly Block Snow;
        public static readonly Block Cactus;
        public static readonly Block Clay;
        public static readonly Block Reeds;
        public static readonly Block Jukebox;
        public static readonly Block OakFence;
        public static readonly Block SpruceFence;
        public static readonly Block BirchFence;
        public static readonly Block JungleFence;
        public static readonly Block DarkOakFence;
        public static readonly Block AcaciaFence;
        public static readonly Block Pumpkin;
        public static readonly Block Netherrack;
        public static readonly Block SoulSand;
        public static readonly Block Glowstone;
        public static readonly Block Portal;
        public static readonly Block LitPumpkin;
        public static readonly Block Cake;
        public static readonly Block UnpoweredRedstoneRepeater;
        public static readonly Block RedstoneRepeater;
        public static readonly Block TrapDoor;
        public static readonly Block MonsterEgg;
        public static readonly Block StoneBrick;
        public static readonly Block BrownMushroomBlock;
        public static readonly Block RedMushroomBlock;
        public static readonly Block IronBars;
        public static readonly Block GlassPane;
        public static readonly Block MelonBlock;
        public static readonly Block PumpkinStem;
        public static readonly Block MelonStem;
        public static readonly Block Vine;
        public static readonly Block OakFenceGate;
        public static readonly Block SpruceFenceGate;
        public static readonly Block BirchFenceGate;
        public static readonly Block JungleFenceGate;
        public static readonly Block DarkOakFenceGate;
        public static readonly Block AcaciaFenceGate;
        public static readonly Block BrickStairs;
        public static readonly Block StoneBrickStairs;
        public static readonly Block Mycelium;
        public static readonly Block WaterLily;
        public static readonly Block NetherBrick;
        public static readonly Block NetherBrickFence;
        public static readonly Block NetherBrickStairs;
        public static readonly Block NetherWart;
        public static readonly Block EnchantingTable;
        public static readonly Block BrewingStand;
        public static readonly Block Cauldron;
        public static readonly Block EndPortal;
        public static readonly Block EndPortalFrame;
        public static readonly Block EndStone;
        public static readonly Block DragonEgg;
        public static readonly Block RedstoneLamp;
        public static readonly Block LitRedstoneLamp;
        public static readonly Block DoubleWoodenSlab;
        public static readonly Block WoodenSlab;
        public static readonly Block Cocoa;
        public static readonly Block SandStoneStairs;
        public static readonly Block EmeraldOre;
        public static readonly Block EnderChest;
        public static readonly Block TripWireHook;
        public static readonly Block TripWire;
        public static readonly Block EmeraldBlock;
        public static readonly Block SpruceStairs;
        public static readonly Block BirchStairs;
        public static readonly Block JungleStairs;
        public static readonly Block CommandBlock;
        public static readonly Block Beacon;
        public static readonly Block CobblestoneWall;
        public static readonly Block FlowerPot;
        public static readonly Block Carrots;
        public static readonly Block Potatoes;
        public static readonly Block WoodenButton;
        public static readonly Block Skull;
        public static readonly Block Anvil;
        public static readonly Block TrappedChest;
        public static readonly Block LightWeightedPressurePlate;
        public static readonly Block HeavyWeightedPressurePlate;
        public static readonly Block UnpoweredComparator;
        public static readonly Block PoweredComparator;
        public static readonly Block DaylightDetector;
        public static readonly Block DaylightDetectorInverted;
        public static readonly Block RedstoneBlock;
        public static readonly Block QuartzOre;
        public static readonly Block Hopper;
        public static readonly Block QuartzBlock;
        public static readonly Block QuartzStairs;
        public static readonly Block ActivatorRail;
        public static readonly Block Dropper;
        public static readonly Block StainedHardenedClay;
        public static readonly Block Barrier;
        public static readonly Block IronTrapDoor;
        public static readonly Block HayBlock;
        public static readonly Block Carpet;
        public static readonly Block HardenedClay;
        public static readonly Block CoalBlock;
        public static readonly Block PackedIce;
        public static readonly Block AcaciaStairs;
        public static readonly Block DarkOakStairs;
        public static readonly Block SlimeBlock;
        public static readonly Block DoublePlant;
        public static readonly Block StainedGlass;
        public static readonly Block StainedGlassPane;
        public static readonly Block Prismarine;
        public static readonly Block SeaLantern;
        public static readonly Block StandingBanner;
        public static readonly Block WallBanner;
        public static readonly Block RedSandStone;
        public static readonly Block RedSandStoneStairs;
        public static readonly Block DoubleStoneSlab2;
        public static readonly Block StoneSlab2;
        public static readonly Block EndRod;
        public static readonly Block ChorusPlant;
        public static readonly Block ChorusFlower;
        public static readonly Block PurpurBlock;
        public static readonly Block PurpurPillar;
        public static readonly Block PurpurStairs;
        public static readonly Block PurpurDoubleSlab;
        public static readonly Block PurpurSlab;
        public static readonly Block EndBricks;
        public static readonly Block Beetroots;
        public static readonly Block GrassPath;
        public static readonly Block EndGateway;
        public static readonly Block RepeatingCommandBlock;
        public static readonly Block ChainCommandBlock;
        public static readonly Block FrostedIce;
        public static readonly Block Magma;
        public static readonly Block NetherWartBlock;
        public static readonly Block RedNetherBrick;
        public static readonly Block BoneBlock;
        public static readonly Block StructureVoid;
        public static readonly Block Observer;
        public static readonly Block WhiteShulkerBox;
        public static readonly Block OrangeShulkerBox;
        public static readonly Block MagentaShulkerBox;
        public static readonly Block LightBlueShulkerBox;
        public static readonly Block YellowShulkerBox;
        public static readonly Block LimeShulkerBox;
        public static readonly Block PinkShulkerBox;
        public static readonly Block GrayShulkerBox;
        public static readonly Block SilverShulkerBox;
        public static readonly Block CyanShulkerBox;
        public static readonly Block PurpleShulkerBox;
        public static readonly Block BlueShulkerBox;
        public static readonly Block BrownShulkerBox;
        public static readonly Block GreenShulkerBox;
        public static readonly Block RedShulkerBox;
        public static readonly Block BlackShulkerBox;
        public static readonly Block StructureBlock;

        static Blocks()
        {
            Air = new BlockAir();
            Stone = new BlockStone();
            Grass = new BlockGrass();
            Dirt = new BlockDirt();
            Cobblestone = new BlockCobblestone();
            Planks = new BlockPlanks();
            Sapling = new BlockSapling();
            Bedrock = new BlockBedrock();
            FlowingWater = new BlockFlowingWater();
            Water = new BlockWater();
            FlowingLava = new BlockFlowingLava();
            Lava = new BlockLava();
            Sand = new BlockSand();
            Gravel = new BlockGravel();
            GoldOre = new BlockGoldOre();
            IronOre = new BlockIronOre();
            CoalOre = new BlockCoalOre();
            Log = new BlockOldLog();
            Log2 = new BlockNewLog();
            Leaves = new BlockOldLeaf();
            Leaves2 = new BlockNewLeaf();
            Sponge = new BlockSponge();
            Glass = new BlockGlass();
            LapisOre = new BlockLapisOre();
            LapisBlock = new BlockLapis();
            Dispenser = new BlockDispenser();
            SandStone = new BlockSandStone();
            NoteBlock = new BlockNote();
            Bed = new BlockBed();
            GoldenRail = new BlockRailPowered();
            DetectorRail = new BlockRailDetector();
            StickyPiston = new BlockStickyPistonBase();
            Web = new BlockWeb();
            TallGrass = new BlockTallGrass();
            DeadBush = new BlockDeadBush();
            Piston = new BlockPistonBase();
            PistonHead = new BlockPistonExtension();
            Wool = new BlockWool();
            PistonExtension = new BlockPistonMoving();
            YellowFlower = new BlockYellowFlower();
            RedFlower = new BlockRedFlower();
            BrownMushroom = new BlockBrownMushroom();
            RedMushroom = new BlockRedMushroom();
            GoldBlock = new BlockGold();
            IronBlock = new BlockIron();
            DoubleStoneSlab = new BlockDoubleStoneSlab();
            StoneSlab = new BlockHalfStoneSlab();
            BrickBlock = new BlockBrick();
            TNT = new BlockTNT();
            Bookshelf = new BlockBookshelf();
            MossyCobblestone = new BlockMossyCobblestone();
            Obsidian = new BlockObsidian();
            Torch = new BlockTorch();
            Fire = new BlockFire();
            MobSpawner = new BlockMobSpawner();
            OakStairs = new BlockOakStairs();
            Chest = new BlockChest();
            RedstoneWire = new BlockRedstoneWire();
            DiamondOre = new BlockDiamondOre();
            DiamondBlock = new BlockDiamond();
            CraftingTable = new BlockWorkbench();
            Wheat = new BlockWheat();
            Farmland = new BlockFarmland();
            Furnace = new BlockFurnace();
            LitFurnace = new BlockLitFurnace();
            StandingSign = new BlockStandingSign();
            OakDoor = new BlockOakDoor();
            SpruceDoor = new BlockSpruceDoor();
            BirchDoor = new BlockBirchDoor();
            JungleDoor = new BlockJungleDoor();
            AcaciaDoor = new BlockAcaciaDoor();
            DarkOakDoor = new BlockDarkOakDoor();
            Ladder = new BlockLadder();
            Rail = new BlockRail();
            StoneStairs = new BlockStoneStairs();
            WallSign = new BlockWallSign();
            Lever = new BlockLever();
            StonePressurePlate = new BlockStonePressurePlate();
            IronDoor = new BlockIronDoor();
            WoodenPressurePlate = new BlockWoodenPressurePlate();
            RedstoneOre = new BlockRedstoneOre();
            LitRedstoneOre = new BlockLitRedstoneOre();
            UnlitRedstoneTorch = new BlockUnlitRedstoneTorch();
            RedstoneTorch = new BlockRedstoneTorch();
            StoneButton = new BlockButtonStone();
            SnowLayer = new BlockSnow();
            Ice = new BlockIce();
            Snow = new BlockSnowBlock();
            Cactus = new BlockCactus();
            Clay = new BlockClay();
            Reeds = new BlockReed();
            Jukebox = new BlockJukebox();
            OakFence = new BlockOakFence();
            SpruceFence = new BlockSpruceFence();
            BirchFence = new BlockBirchFence();
            JungleFence = new BlockJungleFence();
            DarkOakFence = new BlockDarkOakFence();
            AcaciaFence = new BlockAcaciaFence();
            Pumpkin = new BlockPumpkin();
            Netherrack = new BlockNetherrack();
            SoulSand = new BlockSoulSand();
            Glowstone = new BlockGlowstone();
            Portal = new BlockPortal();
            LitPumpkin = new BlockLitPumpkin();
            Cake = new BlockCake();
            UnpoweredRedstoneRepeater = new BlockUnpoweredRedstoneRepeater();
            RedstoneRepeater = new BlockRedstoneRepeater();
            TrapDoor = new BlockTrapDoor();
            MonsterEgg = new BlockSilverfish();
            StoneBrick = new BlockStoneBrick();
            BrownMushroomBlock = new BlockHugeBrownMushroom();
            RedMushroomBlock = new BlockHugeRedMushroom();
            IronBars = new BlockIronPane();
            GlassPane = new BlockGlassPane();
            MelonBlock = new BlockMelon();
            PumpkinStem = new BlockPumpkinStem();
            MelonStem = new BlockMelonStem();
            Vine = new BlockVine();
            OakFenceGate = new BlockOakFenceGate();
            SpruceFenceGate = new BlockSpruceFenceGate();
            BirchFenceGate = new BlockBirchFenceGate();
            JungleFenceGate = new BlockJungleFenceGate();
            DarkOakFenceGate = new BlockDarkOakFenceGate();
            AcaciaFenceGate = new BlockAcaciaFenceGate();
            BrickStairs = new BlockBrickStairs();
            StoneBrickStairs = new BlockStoneBrickStairs();
            Mycelium = new BlockMycelium();
            WaterLily = new BlockLilyPad();
            NetherBrick = new BlockNetherBrick();
            NetherBrickFence = new BlockNetherBrickFence();
            NetherBrickStairs = new BlockNetherBrickStairs();
            NetherWart = new BlockNetherWart();
            EnchantingTable = new BlockEnchantingTable();
            BrewingStand = new BlockBrewingStand();
            Cauldron = new BlockCauldron();
            EndPortal = new BlockEndPortal();
            EndPortalFrame = new BlockEndPotalFrame();
            EndStone = new BlockEndStone();
            DragonEgg = new BlockDragonEgg();
            RedstoneLamp = new BlockRedstoneLight();
            LitRedstoneLamp = new BlockLitRedstoneLight();
            DoubleWoodenSlab = new BlockDoubleWoodSlab();
            WoodenSlab = new BlockHalfWoodSlab();
            Cocoa = new BlockCocoa();
            SandStoneStairs = new BlockSandStoneSiatrs();
            EmeraldOre = new BlockEmeraldOre();
            EnderChest = new BlockEnderChest();
            TripWireHook = new BlockTripWireHook();
            TripWire = new BlockTripWire();
            EmeraldBlock = new BlockEmerald();
            SpruceStairs = new BlockSpruceStairs();
            BirchStairs = new BlockBirchStairs();
            JungleStairs = new BlockJungleStairs();
            CommandBlock = new BlockCommandBlock();
            Beacon = new BlockBeacon();
            CobblestoneWall = new BlockCobblestoneWall();
            FlowerPot = new BlockFlowerPot();
            Carrots = new BlockCarrot();
            Potatoes = new BlockPotato();
            WoodenButton = new BlockButtonWood();
            Skull = new BlockSkull();
            Anvil = new BlockAnvil();
            TrappedChest = new BlockTrapChest();
            LightWeightedPressurePlate = new BlockPressurePlateLightWeighted();
            HeavyWeightedPressurePlate = new BlockPressurePlateHeavyWeighted();
            UnpoweredComparator = new BlockUnpoweredRedstoneComparator();
            PoweredComparator = new BlockRedstoneComparator();
            DaylightDetector = new BlockDaylightDetector();
            DaylightDetectorInverted = new BlockInvertedDaylightDetector();
            RedstoneBlock = new BlockCompressedPowered();
            QuartzOre = new BlockQuartzOre();
            Hopper = new BlockHopper();
            QuartzBlock = new BlockQuartz();
            QuartzStairs = new BlockQuartzStairs();
            ActivatorRail = new BlockActivatorRail();
            Dropper = new BlockDropper();
            StainedHardenedClay = new BlockStainedHardenedClay();
            Barrier = new BlockBarrier();
            IronTrapDoor = new BlockIronTrapDoor();
            HayBlock = new BlockHay();
            Carpet = new BlockCarpet();
            HardenedClay = new BlockHardenedClay();
            CoalBlock = new BlockCoal();
            PackedIce = new BlockPackedIce();
            AcaciaStairs = new BlockAcaciaStairs();
            DarkOakStairs = new BlockDarkOakStairs();
            SlimeBlock = new BlockSlime();
            DoublePlant = new BlockDoublePlant();
            StainedGlass = new BlockStainedGlass();
            StainedGlassPane = new BlockStainedGlassPane();
            Prismarine = new BlockPrismarine();
            SeaLantern = new BlockSeaLantern();
            StandingBanner = new BlockBannerStanding();
            WallBanner = new BlockBannerHanging();
            RedSandStone = new BlockRedSandStone();
            RedSandStoneStairs = new BlockRedSandStoneStairs();
            DoubleStoneSlab2 = new BlockDoubleStoneSlabNew();
            StoneSlab2 = new BlockHalfStoneSlabNew();
            EndRod = new BlockEndRod();
            ChorusPlant = new BlockChorusPlant();
            ChorusFlower = new BlockChorusFlower();
            PurpurBlock = new BlockPurpur();
            PurpurPillar = new BlockPurpurPillar();
            PurpurStairs = new BlockPurpurStairs();
            PurpurDoubleSlab = new BlockPurpurDoubleSlab();
            PurpurSlab = new BlockPurpurHalfSlab();
            EndBricks = new BlockEndBricks();
            Beetroots = new BlockBeetroot();
            GrassPath = new BlockGrassPath();
            EndGateway = new BlockEndGateway();
            RepeatingCommandBlock = new BlockCommandBlockRepeating();
            ChainCommandBlock = new BlockCommandBlockChain();
            FrostedIce = new BlockFrostedIce();
            Magma = new BlockMagma();
            NetherWartBlock = new BlockNetherWartBlock();
            RedNetherBrick = new BlockRedNetherBrick();
            BoneBlock = new BlockBone();
            StructureVoid = new BlockStructureVoid();
            Observer = new BlockObserver();
            WhiteShulkerBox = new BlockShulkerBoxWhite();
            OrangeShulkerBox = new BlockShulkerBoxOrange();
            MagentaShulkerBox = new BlockShulkerBoxMagenta();
            LightBlueShulkerBox = new BlockShulkerBoxLightBlue();
            YellowShulkerBox = new BlockShulkerBoxYellow();
            LimeShulkerBox = new BlockShulkerBoxLime();
            PinkShulkerBox = new BlockShulkerBoxPink();
            GrayShulkerBox = new BlockShulkerBoxGray();
            SilverShulkerBox = new BlockShulkerBoxSilver();
            CyanShulkerBox = new BlockShulkerBoxCyan();
            PurpleShulkerBox = new BlockShulkerBoxPurple();
            BlueShulkerBox = new BlockShulkerBoxBlue();
            BrownShulkerBox = new BlockShulkerBoxBrown();
            GreenShulkerBox = new BlockShulkerBoxGreen();
            RedShulkerBox = new BlockShulkerBoxRed();
            BlackShulkerBox = new BlockShulkerBoxBlack();
            StructureBlock = new BlockStructure();
        }
    }
}